### ISSUE TITLE
Feature: Prevent github notification spamming

### ISSUE THREAD

**Issue by abose** [abose/github-issues-import#1]
When issues with `@user` mentions are copied, GitHub will send email notifications to the tagged used in his inbox. When cloning large repos, a flood of notifications will be sent for each issue having a mentioned user. There should be a way to limit this behavior so that a user receiv3es only a maximum of n notifications.

- [x] validate whether `@menbtions` only produce notifications
- [x] Validate that `[user](https://guthub.com/user)` does not generate notification emails.
- [ ] Modify code so that only a maximum of 3 notifications is sent to a mentioned user when cloning repository issues. This can be done by changing `@menbtions`  to hyperlinks `[user](https://guthub.com/user)` if that doesn't generate notifications or some other escape mecanisms.
- [x] Apply the fix to comments as well as issue body.

**Comment by TapanManu** [comment]
[user](https://guthub.com/user)  is also generating email notifications at mentioned user's email
Refer [here](https://github.com/TapanManu/PyGit/issues/14#issuecomment-904347189)

**Comment by TapanManu** [comment]
**Task 1 further updates**
Email notifications are send for user-names even without @ mentions

**Comment by abose** [comment]
We added an escape symbol when encountering `@` mentions. This prevents notifications from being generated.

**Comment by abose** [comment]
No notifications will be sent on issue copies now. closing.
